<div style="font-size: 36px;">
COMS W4111 -- Introduction to Databases, Spring 2026<br>Lecture 7 Examples
</div>

# Initialize Environment

In [ ]:
%load_ext sql

In [ ]:
# %magic

In [ ]:
# %pip install pandas
# %pip install pymysql

In [ ]:
db_url = "mysql+pymysql://root:dbuserdbuser@localhost"

In [ ]:
# This is a hack to fix a version problem/incompatibility  with some of the packages and magics.
#
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [ ]:
%sql $db_url

In [18]:
import pandas

In [ ]:
from sqlalchemy import create_engine, text

In [ ]:
import pymysql

# MongoDB

## Configuration

In [ ]:
# %pip install "pymongo[srv]"

In [ ]:
# %pip install pymongo

In [1]:
from pymongo import MongoClient

In [2]:
import pymongo

In [3]:
mongourl = "mongodb+srv://dbuser:1wBKjviMlModwMZw@cluster0.t8qdk.mongodb.net/?appName=Cluster0"

In [4]:
client = MongoClient(mongourl, server_api=pymongo.server_api.ServerApi(
   version="1", strict=True, deprecation_errors=True))

In [5]:
try:
    # start example code here
    # end example code here
    client.admin.command("ping")
    print("Connected successfully")
    # other application code
    # client.close()
except Exception as e:
    raise Exception(
        "The following error occurred: ", e)

Connected successfully

# Some Examples

In [6]:
filter={
    'orderNumber': 10100
}
result = client['classicmodels']['ordersall'].find(
  filter=filter
)

In [7]:
result

In [8]:
list(result)

[{'_id': ObjectId('6238bdc4dbfa1c05c4e69dee'),
  'orderNumber': 10100,
  'orderDate': '2003-01-06',
  'requiredDate': '2003-01-13',
  'shippedDate': '2003-01-10',
  'status': 'Shipped',
  'customerNumber': 363,
  'orderLines': [{'productCode': 'S24_3969',
    'quantityOrdered': 49,
    'priceEach': 35.29},
   {'productCode': 'S18_2248', 'quantityOrdered': 50, 'priceEach': 55.09},
   {'productCode': 'S18_1749', 'quantityOrdered': 30, 'priceEach': 136.0},
   {'productCode': 'S18_4409', 'quantityOrdered': 22, 'priceEach': 75.46}],
  'comments': []}]

In [11]:
filter={
    'orderNumber': 10100,
    'customerNumber': 364
}
project = {
    'orderNumber': 1,
    'orderDate': 1,
    'status': 1,
    'customerNumber': 1
}

result = client['classicmodels']['ordersall'].find(
  filter=filter,
    projection=project
)

In [12]:
list(result)

[]

In [13]:
result = client['classicmodels']['ordersall'].aggregate([
    {
        '$match': {
            'orderNumber': 10100
        }
    }, {
        '$lookup': {
            'from': 'customers', 
            'localField': 'customerNumber', 
            'foreignField': 'customerNumber', 
            'as': 'customer'
        }
    }, {
        '$unwind': '$customer'
    }, {
        '$project': {
            '_id': 0, 
            'orderNumber': 1, 
            'orderDate': 1, 
            'status': 1, 
            'customerNumber': 1, 
            'customerName': '$customer.customerName', 
            'customerNumber_cust': '$customer.customerNumber'
        }
    }, {
        '$project': {
            'orderNumber': 1, 
            'orderDate': 1, 
            'status': 1, 
            'customerNumber': 1, 
            'customerName': 1
        }
    }
])

In [14]:
list(result)

[{'orderNumber': 10100,
  'orderDate': '2003-01-06',
  'status': 'Shipped',
  'customerNumber': 363,
  'customerName': 'Online Diecast Creations Co.'}]

In [32]:
result = client['classicmodels']['ordersall'].aggregate([
    {
        '$match': {
            'customerNumber': 363
        }
    }, {
        '$lookup': {
            'from': 'customers', 
            'localField': 'customerNumber', 
            'foreignField': 'customerNumber', 
            'as': 'customer'
        }
    }, {
        '$unwind': '$customer'
    }, {
        '$project': {
            '_id': 0,
            'orderNumber': 1, 
            'orderDate': 1, 
            'status': 1, 
            'customerNumber': 1, 
            'customerName': '$customer.customerName', 
            'customerNumber': '$customer.customerNumber'
        }
    }
])

In [33]:
df = pandas.DataFrame(result)
df

,orderNumber,orderDate,status,customerNumber,customerName
0,10100,2003-01-06,Shipped,363,Online Diecast Creations Co.
1,10192,2003-11-20,Shipped,363,Online Diecast Creations Co.
2,10322,2004-11-04,Shipped,363,Online Diecast Creations Co.

In [34]:
result = client['classicmodels']['ordersall'].aggregate([
    {
        '$match': {
            'customerNumber': 363
        }
    }, {
        '$lookup': {
            'from': 'customers', 
            'localField': 'customerNumber', 
            'foreignField': 'customerNumber', 
            'as': 'customer'
        }
    }, {
        '$unwind': '$customer'
    }, {
        '$project': {
            'customerNumber': 1, 
            'status': 1, 
            'orderDate': 1, 
            'customerName': '$customer.customerName', 
            '_id': 0
        }
    }
])

In [35]:
df2 = pandas.DataFrame(result)
df2

    orderDate   status  customerNumber                  customerName
0  2003-01-06  Shipped             363  Online Diecast Creations Co.
1  2003-11-20  Shipped             363  Online Diecast Creations Co.
2  2004-11-04  Shipped             363  Online Diecast Creations Co.